
jobs:
  web-deploy:
  web-deploy:
    name: ğŸ‰ Deploy
    name: ğŸ‰ Deploy
    runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    steps:
    - name: ğŸšš Get latest code
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
      uses: actions/checkout@v2
